### ISSUE TITLE
TypeScript 5.0 unfortunately breaks most examples

### ISSUE THREAD

**Issue by tmcw** [itsdouges/typescript-transformer-handbook#30]
[Example in the playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5xugZlCI4DkMAnmAKaoDGUwYMBA3AFBOUQB2q8MUynW0EGSgAuDKgB0AFV79BwgGLJKMaMQA8mCQGUIAVyiUyC4ABsyAPjgBeOG3YwyAD3jWrAbyZw4UMjAPscKj6hsZmZDYeXt52HFxwAG7AqMCqUDZwABTsEAAmZGJaAHJ5ZACUhZIl+ZFwnjExwFhZWskAkvkOTcDC2aVlZXXRDd6oAO6plAAWWTn5EhSUyOS5Us4wg-UjDUuoEQQARsgHZKYEIsPbMb7+UIH2ji4SWMppxBLUZMiOHWRdWD0oJkiKRFjQ6AQysxLttdvswKY9ABzYCcc4wq43AKxBzrZ6vNQfXzfMi-f6A4E8PioARQIRQVCQ5hXOAAXwx7IxWLu4gkSRSMAAosopgBhKZmXJ9fIAGkSyVS0DlD3WUMurOhDW5gS0-NS1TImWCBiMJnMcr1aTV3g1TFtTGckFgcHyLz0pm4shp8igDCAA)

Unfortunately, most examples in this guide (and most of my code too 😆 ) is broken in TypeScript 5.0 because the `transformer` type now requires its return to be a `SourceFile`, not just a `Node`.

**Comment by hax** [comment]
Another problem is `ts.getMutableClone` seems have been totally removed. (though it already be deprecated in previous versions).

**Comment by itsdouges** [comment]
Happy to have a pull request fixing things up! Unfortunately I won't have time to fix things.
